### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by mremes** [AaaDee/Lautapelikirppis#1]
Katselmoitu koodi ladattu 6.10.2018 klo 15:45.

# Käyttötapaukset
* Kokeilin muokata tuotetta. Muokkausformin olisi hyvä palauttaa aikaisemmat arvot. Esim. BGG-tunnuksen joutuu kirjoittamaan uudestaan.
* Lienee tarkoitus, että myytävät pelejä (Item) vastaisi Game-taulussa vastaava rivi, jotta myytävän pelin tietoja voisi tarkastella?
* Saavutettavuus on heikonlaista, kun tyylitykset, html-alt-arvot eivät ole kunnossa ja esim. Lautapelikirppis-otsikon linkki ei vie mihinkään.

# Koodi
## Yleistä
1. Koodin formatointi
* Projektissa ei näytä olevan koodityyliä, eli rupea käyttämään jotakin tyyliohjetta. [PEP8](https://www.python.org/dev/peps/pep-0008/) on turvallinen vaihtoehto.
2. Arkkitehtuuri
* Model-, View- ja Controller-toiminnallisuudet on eroteltu siististi – :+1:!
* Tietokantatiedosto (application/games.db) pitäisi jättää pois versionhallinnasta.
### auth
* Käytä User-luokassa [flask-loginin tarjoamaa UserMixin -luokkaa](https://flask-login.readthedocs.io/en/latest/_modules/flask_login/mixins.html#UserMixin) autentikointiin liittyvien metodien oletuspalautusarvojen käyttämiseksi.
* Poista turhat kommentit
### games
* Muuta bgg -> bgg-id Game- ja GameForm-luokissa.
* Yksikirjaimiset muuttujanimet pois ;)
### items
* Miksi price on kokonaisluku eikä float? Jos muutat floatiksi, niin validoi formissa, että käyttäjä syöttää sadasosan desimaaleja.
* Jos syöttää formiin floatin, niin form hälyttää että `This is required.` eikä anna oikeaa virheilmoitusta.
### items
Muuta Item.items_total metodissa:
```
         stmt = text("SELECT COUNT(Item.id) FROM Item"
                    " WHERE Item.sold = '0'")
```
->
```
stmt = """
SELECT COUNT(Item.id)
FROM Item
WHERE Item.sold = '0'
"""
```

Muuta lisäksi query muotoon:
```
SELECT COUNT(id)
FROM Item
WHERE NOT sold
```

## Templaatit
* Periytä error-viesti layout.html:stä (ks. auth/loginform.html).
* Tyylitä taulukot.
* Tyylitä nav-menu.

# Muuta
* Dokumentaation Markdown-tyylitys kuntoon (otsikot, linkit, listat, yms.)

**Comment by AaaDee** [comment]
Kiitoksia työhön perehtymisestä ja asiantuntevista kommenteista! Näiden pohjalta on hyvä lähteä loppurutistukseen!
